# Generated by Django 5.2.10 on 2026-01-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of work performed'),
        ),
    ]
