# Generated by Django 5.2.10 on 2026-01-13 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_timeentry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='performer_name',
            field=models.CharField(blank=True, help_text='Optional name of person working this session', max_length=100),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='api.employee'),
        ),
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color for UI', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(blank=True, help_text='If null, tag is global (available for all roles)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_tags', to='api.jobcodecategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='timeentry',
            name='activity_tags',
            field=models.ManyToManyField(blank=True, related_name='time_entries', to='api.activitytag'),
        ),
    ]
