# Generated by Django 5.2.10 on 2026-01-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_role_based_redesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='performer_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='pin_hash',
            field=models.CharField(blank=True, help_text='Hashed 4-digit PIN for authentication', max_length=128),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='api.employee'),
        ),
    ]
