# Generated by Django 5.2.10 on 2026-01-13 18:54

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_timeentry_performer_name_employee_pin_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.time_entry_photo_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.timeentry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
